// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const AMAZON_BEDROCK_MODELS = {
	"eu.anthropic.claude-opus-4-6-v1": {
		id: "eu.anthropic.claude-opus-4-6-v1",
		name: "Claude Opus 4.6 (EU)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.eu-central-1.amazonaws.com",
		reasoning: true,
		thinkingLevelMap: {"xhigh":"max"},
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 200000,
		maxTokens: 128000,
	} satisfies Model<"bedrock-converse-stream">,
} as const;
