// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const GOOGLE_MODELS = {
	"gemini-3.1-flash-lite-preview": {
		id: "gemini-3.1-flash-lite-preview",
		name: "Gemini 3.1 Flash Lite Preview",
		api: "google-generative-ai",
		provider: "google",
		baseUrl: "https://generativelanguage.googleapis.com/v1beta",
		reasoning: true,
		thinkingLevelMap: {"off":null},
		input: ["text", "image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 65536,
	} satisfies Model<"google-generative-ai">,
} as const;
