// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const MISTRAL_MODELS = {
	"mistral-medium-3.5": {
		id: "mistral-medium-3.5",
		name: "Mistral Medium 3.5",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.5,
			output: 7.5,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 262144,
	} satisfies Model<"mistral-conversations">,
} as const;
