// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const XAI_MODELS = {
	"grok-3": {
		id: "grok-3",
		name: "Grok 3",
		api: "openai-completions",
		provider: "xai",
		baseUrl: "https://api.x.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.75,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
	"grok-3-fast": {
		id: "grok-3-fast",
		name: "Grok 3 Fast",
		api: "openai-completions",
		provider: "xai",
		baseUrl: "https://api.x.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 1.25,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
	"grok-code-fast-1": {
		id: "grok-code-fast-1",
		name: "Grok Code Fast 1",
		api: "openai-completions",
		provider: "xai",
		baseUrl: "https://api.x.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.2,
			output: 1.5,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 32768,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
